### ISSUE TITLE
Use Rito API for !lol instead of op.gg

### ISSUE THREAD

**Issue by ILiedAboutCake** [hayksaakian/chatbots#5]
Op.gg sux and is good for returning back incorrect data.

You can pull summoner data right from riot, with the following 2-3 API calls

To get the summoners ID number (needed for the 2nd API call, only needs to be done once):
https://na.api.pvp.net/api/lol/na/v1.4/summoner/by-name/NeoD%C3%A9stiny?api_key=API_KEY_REMOVED

To get their last game data, the following call can be made:
https://na.api.pvp.net/api/lol/na/v1.3/game/by-summoner/SUMMONER_ID/recent?api_key=API_KEY_REMOVED

To get their live game data(e-stalking) you can use:
https://na.api.pvp.net/observer-mode/rest/consumer/getSpectatorGameInfo/NA1/SUMMONER_ID?api_key=API_KEY_REMOVED

RITO documentation and key registration can be found at: https://developer.riotgames.com/

**Comment by hayksaakian** [comment]
Thnx m80

**Comment by hayksaakian** [comment]
#fixed but timestamps are still messed up
